# Generated by Django 4.1.5 on 2023-01-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('meaning', models.CharField(max_length=70)),
                ('exemple', models.CharField(max_length=70)),
            ],
        ),
    ]
