# Generated by Django 4.1.5 on 2023-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishdashboardAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressao',
            name='foto',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
