# Generated by Django 4.1.5 on 2023-01-15 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishdashboardAPP', '0002_expressao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
